name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pandoc
      - name: "Generate slides"
        run: |
          cmake -Bbuild -Hslides
          cmake --build build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/output/beamer/
